version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    volumes:
      - minecraft:/data
    env_file:
      - .env
    ports:
      - 25565:25565/udp
      - 25565:25565/tcp

  remote-minecraft-rcon-cli:
    image: noahjahn/docker-remote-minecraft-rcon-cli
    restart: always
    env_file:
      - .env.remote-minecraft-rcon-cli
    ports:
      - 3333:3333

  database:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: remote-minecraft-rcon-cli
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: remote-minecraft-rcon-cli

volumes:
  minecraft:
  postgres-data:
